name: Build WinObjEx64 and Plugins

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allow manual runs from the Actions tab

env:
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build WinObjEx64
        working-directory: ./Source
        run: msbuild /m /p:Platform=x64 /p:Configuration=Release WinObjEx64.sln

      - name: Build WinObjEx64 Plugins
        working-directory: ./Source
        run: msbuild /m /p:Platform=x64 /p:Configuration=Release WinObjEx64_Plugins.sln

      - name: Upload WinObjEx64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinObjEx64
          path: |
            Source\WinObjEx64\output\x64\Release\*.exe

      - name: Upload WinObjEx64 Plugins artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinObjEx64_Plugins
          path: |
            Source\Plugins\*\output\x64\Release\*.dll
