name: Build WinObjEx64 and Plugins

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allow manual runs from the Actions tab

env:
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build WinObjEx64
        working-directory: ./Source
        run: msbuild /m /p:Platform=x64 /p:Configuration=Release WinObjEx64.sln

      - name: Build WinObjEx64 package
        run: |
          mkdir Package\Application
          copy Source\WinObjEx64\output\x64\Release\bin\WinObjEx64.exe Package\Application
          copy Docs\WinObjEx64.chm Package\Application
          
      - name: Build WinObjEx64 Plugins
        working-directory: ./Source
        run: msbuild /m /p:Platform=x64 /p:PostBuildEventUseInBuild=false /p:Configuration=Release WinObjEx64_Plugins.sln

      - name: Gather all plugin DLLs
        run: |
          mkdir Package\Plugins
          copy Source\Plugins\ApiSetView\output\x64\Release\bin\ApiSetView.dll Package\Plugins
          copy Source\Plugins\Sonar\output\x64\Release\bin\Sonar.dll Package\Plugins
          copy Source\Plugins\ExamplePlugin\output\x64\Release\bin\ExamplePlugin.dll Package\Plugins
          copy Source\Plugins\ImageScope\output\x64\Release\bin\ImageScope.dll Package\Plugins

      - name: Upload WinObjEx64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WinObjEx64
          path: Package\Application\*

      - name: Upload WinObjEx64 Plugins artifact (zip)
        uses: actions/upload-artifact@v4
        with:
          name: WinObjEx64_Plugins
          path: Package\Plugins\*
